# Generated by Django 4.2.2 on 2023-06-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='sex',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
