# Generated by Django 4.2.2 on 2023-06-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpart', '0003_useraccount_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/avatars/'),
        ),
    ]
