# Generated by Django 4.2.2 on 2023-06-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpart', '0004_alter_useraccount_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
