# Generated by Django 4.2.2 on 2023-06-29 16:30

from django.db import migrations, models
import userpart.models


class Migration(migrations.Migration):

    dependencies = [
        ('userpart', '0006_remove_useraccount_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=userpart.models.user_directory_path),
        ),
    ]
