# Generated by Django 4.2.2 on 2023-06-29 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpart', '0009_alter_userrelations_liked_persons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelations',
            name='liked_persons',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrelations',
            name='match_persons',
            field=models.ManyToManyField(blank=True, null=True, related_name='match', to=settings.AUTH_USER_MODEL),
        ),
    ]
