# Generated by Django 4.2.2 on 2023-06-30 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpart', '0010_alter_userrelations_liked_persons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelations',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
    ]
