# Generated by Django 4.2.2 on 2023-06-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpart', '0011_alter_userrelations_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrelations',
            name='latitude',
            field=models.FloatField(blank=True, default=1, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrelations',
            name='longitude',
            field=models.FloatField(blank=True, default=1.2, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
