# Generated by Django 4.2.2 on 2023-06-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpart', '0012_userrelations_latitude_userrelations_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelations',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='userrelations',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
