# Generated by Django 4.2.2 on 2023-06-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpart', '0013_alter_userrelations_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrelations',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userrelations',
            name='longitude',
        ),
    ]
