# Generated by Django 4.2.2 on 2023-06-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpart', '0014_remove_userrelations_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
